<!DOCTYPE html>
<html lang="en">
<head>
<title>Simile</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet"
	href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css"
	href="css/style.css" />
<script
	src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script
	src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script
	src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<style>
</style>
<body>

	<div class="jumbotron text-center mb-0">
		<h1>Simile</h1>
	</div>
	<nav class="navbar navbar-expand-sm bg-danger navbar-dark mb-5">
		<ul class="navbar-nav">
		</ul>
	</nav>

	<div class="container text-center">
		<form>
			<label>社員ID</label>
			<input type="text" class="input-field"
				placeholder="User name or Email" required>
			<p>
			<label>部署コード</label>
			<input type="text" class="input-field"
				placeholder="User name or Email" required>
			<p>
			<label>ログインID</label>
			<input type="text" class="input-field"
				placeholder="User name or Email" required>
			<p>
			<label>ログインパスワード</label>
			<input type="text" class="input-field"
				placeholder="User name or Email" required>
			<p>
			<label>フリガナ</label>
			<input type="text" class="input-field"
				placeholder="User name or Email" required>
			<p>
			<label>郵便番号</label>
			<input type="text" class="input-field"
				placeholder="User name or Email" required>
			<p>
			<label>住所1</label>
			<input type="text" class="input-field"
				placeholder="User name or Email" required>
			<p>
			<label>住所2</label>
			<input type="text" class="input-field"
				placeholder="User name or Email" required>
			<p>
			<label>電話番号</label>
			<input type="text" class="input-field"
				placeholder="User name or Email" required>
			<p>
			<label>携帯番号</label>
			<input type="text" class="input-field"
				placeholder="User name or Email" required>
			<p>
			<label>メール</label>
			<input type="text" class="input-field"
				placeholder="User name or Email" required>
			<p>
			<button class="submit">Join</button>
		</form>
	</div>

	<div class="jumbotron text-center mb-0 mt-5">
		<p>Footer</p>
	</div>

</body>
</html>
